/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodel.ChucVu;
import domainmodel.CuaHang;
import domainmodel.NhanVien;
import iservice.IChucVuService;
import iservice.ICuaHangService;
import iservice.INhanVienService;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ChucVuService;
import service.CuaHangService;
import service.NhanVienService;
import viewmodel.ViewModelChucVu;
import viewmodel.ViewModelCuaHang;
import viewmodel.ViewModelNhanVien;

/**
 *
 * @author Admin
 */
public class ViewNhanVien extends javax.swing.JFrame {

    private INhanVienService iNhanVienService = new NhanVienService();
    private IChucVuService iChucVuService = new ChucVuService();
    private ICuaHangService iCuaHangService = new CuaHangService();

    /**
     * Creates new form ViewNhanVien
     */
    public ViewNhanVien() {
        initComponents();
        loadComBoBoxTenChucVu();
        loadComBoBoxTenCuaHang();
        loadTable(iNhanVienService.getAll());
    }

    public void loadTable(ArrayList<ViewModelNhanVien> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblNhanVienForm.getModel();
        defaultTableModel.setRowCount(0);
        for (ViewModelNhanVien viewModelNhanVien : list) {
            defaultTableModel.addRow(new Object[]{
                viewModelNhanVien.getMa(), viewModelNhanVien.getHo(), viewModelNhanVien.getTenDem(), viewModelNhanVien.getTen(), viewModelNhanVien.getGioiTinh(), viewModelNhanVien.getNgaySinh(), viewModelNhanVien.getDiaChi(), viewModelNhanVien.getSoDienThoai(), viewModelNhanVien.getMatKhau(), viewModelNhanVien.getTenCuaHang(), viewModelNhanVien.getTenChucVu(), viewModelNhanVien.getTrangThai() == 0 ? "Làm" : "Nghỉ"
            });
        }
    }

    // load comboboxChucVu
    public void loadComBoBoxTenChucVu() {
        List<ViewModelChucVu> list = iChucVuService.getAll();
        for (ViewModelChucVu viewModelChucVu : list) {
            String tenChucVu = viewModelChucVu.getTen();
            cbbChucVu.addItem(tenChucVu);
        }
    }

    // loadComBoBoxByTenCuaHang
    public void loadComBoBoxTenCuaHang() {
        List<ViewModelCuaHang> list = iCuaHangService.getAll();
        for (ViewModelCuaHang viewModelCuaHang : list) {
            String tenCuaHang = viewModelCuaHang.getTen();
            cbbCuaHang.addItem(tenCuaHang);     
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenDem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVienForm = new javax.swing.JTable();
        cbbChucVu = new javax.swing.JComboBox<>();
        cbbCuaHang = new javax.swing.JComboBox<>();
        rdoLam = new javax.swing.JRadioButton();
        rdoNghi = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhân Viên ");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên");

        jLabel4.setText("Tên Đệm");

        jLabel5.setText("Họ");

        jLabel6.setText("Giới Tính");

        jLabel7.setText("Ngày Sinh");

        jLabel8.setText("Địa Chỉ");

        jLabel9.setText("SĐT");

        jLabel10.setText("Mật Khẩu ");

        jLabel11.setText("Tên Chức Vụ");

        jLabel12.setText("Tên Cửa hàng");

        jLabel13.setText("Trạng thái");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblNhanVienForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ", "Tên Đệm", "Tên", "Giới Tính", "Ngày Sinh", "Địa Chỉ", "SĐT", "Mật khẩu", "Cửa hàng", "Chức vụ", "Trạng Thái"
            }
        ));
        tblNhanVienForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienFormMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVienForm);

        cbbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChucVuActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoLam);
        rdoLam.setText("Làm");

        buttonGroup1.add(rdoNghi);
        rdoNghi.setText("Nghỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(txtTen)
                                        .addComponent(txtTenDem)
                                        .addComponent(txtHo)
                                        .addComponent(txtGioiTinh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoLam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoNghi)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel12))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgaySinh)
                                    .addComponent(txtDiaChi)
                                    .addComponent(txtSDT)
                                    .addComponent(txtMatKhau)
                                    .addComponent(cbbChucVu, 0, 123, Short.MAX_VALUE)
                                    .addComponent(cbbCuaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem)
                                .addGap(40, 40, 40)
                                .addComponent(btnSua)
                                .addGap(40, 40, 40)
                                .addComponent(btnXoa)))
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(cbbCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoLam)
                    .addComponent(rdoNghi))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public ViewModelNhanVien getData() {
        ViewModelNhanVien viewModelNhanVien = new ViewModelNhanVien();
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String tenDem = txtTenDem.getText();
        String ho = txtHo.getText();
        String gioiTinh = txtGioiTinh.getText();
        String ngaySinh = txtNgaySinh.getText();
        String diaChi = txtDiaChi.getText();
        String soDienThoai = txtSDT.getText();
        String matKhau = txtMatKhau.getText();

        // lấy ra tên 
        String tenCH = cbbCuaHang.getSelectedItem().toString();
        String tenCV = cbbChucVu.getSelectedItem().toString();


        viewModelNhanVien.setMa(ma);
        viewModelNhanVien.setTen(ten);
        viewModelNhanVien.setTenDem(tenDem);
        viewModelNhanVien.setHo(ho);
        viewModelNhanVien.setGioiTinh(gioiTinh);

        viewModelNhanVien.setDiaChi(diaChi);
        viewModelNhanVien.setSoDienThoai(soDienThoai);
        viewModelNhanVien.setMatKhau(matKhau);
        
        viewModelNhanVien.setTenCuaHang(tenCH);
        viewModelNhanVien.setTenChucVu(tenCV);
        // thêm ngày sinh vào 
        try {
            LocalDate localDate = LocalDate.parse(ngaySinh);
            viewModelNhanVien.setNgaySinh(java.sql.Date.valueOf(localDate));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "chua dung dinh dang ngày tạo");
            return null;
        }

        // theem rdo vao
        if (rdoLam.isSelected()) {
            viewModelNhanVien.setTrangThai(0);
        } else {
            viewModelNhanVien.setTrangThai(1);
        }
        return viewModelNhanVien;
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ViewModelNhanVien viewModelNhanVien = getData();
        JOptionPane.showMessageDialog(this, iNhanVienService.insert(viewModelNhanVien));
        loadTable(iNhanVienService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblNhanVienForm.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xoá");
            return;
        }
        String ma = tblNhanVienForm.getValueAt(row, 0).toString();
        JOptionPane.showMessageDialog(this, iNhanVienService.delete(ma));
        loadTable(iNhanVienService.getAll());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblNhanVienForm.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
            return;
        }
        ViewModelNhanVien viewModelNhanVien = getData();
        String ma = tblNhanVienForm.getValueAt(row, 0).toString();
        JOptionPane.showMessageDialog(this, iNhanVienService.update(ma, viewModelNhanVien));
        loadTable(iNhanVienService.getAll());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblNhanVienFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienFormMouseClicked
        int row = tblNhanVienForm.getSelectedRow();
        String ma = tblNhanVienForm.getValueAt(row, 0).toString();
        String ho = tblNhanVienForm.getValueAt(row, 1).toString();
        String tenDem = tblNhanVienForm.getValueAt(row, 2).toString();
        String ten = tblNhanVienForm.getValueAt(row, 3).toString();
        String gioiTinh = tblNhanVienForm.getValueAt(row, 4).toString();
        String ngaySinh = tblNhanVienForm.getValueAt(row, 5).toString();
        String diaChi = tblNhanVienForm.getValueAt(row, 6).toString();
        String sdt = tblNhanVienForm.getValueAt(row, 7).toString();
        String matKhau = tblNhanVienForm.getValueAt(row, 8).toString();
        String cuaHang = tblNhanVienForm.getValueAt(row, 9).toString();
        String chucVu = tblNhanVienForm.getValueAt(row, 10).toString();
        String trangThai = tblNhanVienForm.getValueAt(row, 11).toString();
        if (trangThai.equals("Làm")) {
            rdoLam.setSelected(true);
        } else {
            rdoNghi.setSelected(true);
        }
        txtMa.setText(ma);
        txtHo.setText(ho);
        txtTenDem.setText(tenDem);
        txtTen.setText(ten);
        txtGioiTinh.setText(gioiTinh);
        txtNgaySinh.setText(ngaySinh);
        txtDiaChi.setText(diaChi);
        txtSDT.setText(sdt);
        txtMatKhau.setText(matKhau);
        cbbCuaHang.setSelectedItem(cuaHang);
        cbbChucVu.setSelectedItem(chucVu);

    }//GEN-LAST:event_tblNhanVienFormMouseClicked

    private void cbbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChucVuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbChucVu;
    private javax.swing.JComboBox<String> cbbCuaHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoLam;
    private javax.swing.JRadioButton rdoNghi;
    private javax.swing.JTable tblNhanVienForm;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    // End of variables declaration//GEN-END:variables
}
