/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import iservice.IGioHangService;
import iservice.IKhachHangSerivce;
import iservice.INhanVienService;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.DefaultMetalTheme;
import javax.swing.table.DefaultTableModel;
import service.GioHangService;
import service.KhachHangService;
import service.NhanVienService;
import viewmodel.ViewModelGioHang;
import viewmodel.ViewModelKhachHang;
import viewmodel.ViewModelNhanVien;

/**
 *
 * @author Admin
 */
public class ViewGioHang extends javax.swing.JFrame {

    public IGioHangService iGioHangService = new GioHangService();
    public IKhachHangSerivce iKhachHangSerivce = new KhachHangService();
    public INhanVienService iNhanVienService = new NhanVienService();

    /**
     * Creates new form ViewGioHang
     */
    public ViewGioHang() {
        initComponents();
        loadTable(iGioHangService.getAll());
        comBoBoxMaKH();
        comBoBoxMaNV();
    }

    public void loadTable(ArrayList<ViewModelGioHang> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblGioHangFrom.getModel();
        defaultTableModel.setRowCount(0);
        for (ViewModelGioHang viewModelGioHang : list) {
            defaultTableModel.addRow(new Object[]{
                viewModelGioHang.getMaKH(), viewModelGioHang.getMaNV(), viewModelGioHang.getMa(), viewModelGioHang.getNgayTao(), viewModelGioHang.getNgayThanhToan(), viewModelGioHang.getTenNguoiNhan(), viewModelGioHang.getDiaChi(), viewModelGioHang.getSoDienThoai(), viewModelGioHang.getTinhTrang() == 1 ? "Chờ thanh toán" : "Huỷ", viewModelGioHang.getId()
            });
        }
    }

    public void comBoBoxMaKH() {
        ArrayList<ViewModelKhachHang> list = iKhachHangSerivce.getAll();
        for (ViewModelKhachHang viewModelKhachHang : list) {
            String maKH = viewModelKhachHang.getMa();
            cbbMaKH.addItem(maKH);
        }
    }

    public void comBoBoxMaNV() {
        ArrayList<ViewModelNhanVien> list = iNhanVienService.getAll();
        for (ViewModelNhanVien viewModelNhanVien : list) {
            String maNV = viewModelNhanVien.getMa();
            cbbMaNV.addItem(maNV);
        }
    }

    public ViewModelGioHang getData() {
        ViewModelGioHang viewModelGioHang = new ViewModelGioHang();
        String maKH = cbbMaKH.getSelectedItem().toString();
        String maNV = cbbMaNV.getSelectedItem().toString();
        String ma = txtMa.getText();
        String ngayTao = txtNgayTao.getText();
        String ngayThanhToan = txtNgayThanhToan.getText();
        String tenNguoiNhan = txtNguoiNhan.getText();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSDT.getText();
        if (rdoChoThanhToan.isSelected()) {
            viewModelGioHang.setTinhTrang(1);
        } else {
            viewModelGioHang.setTinhTrang(0);
        }
        if (ma.trim().equals("") || ngayTao.trim().equals("") || ngayThanhToan.trim().equals("") || tenNguoiNhan.trim().equals("") || diaChi.trim().equals("") || sdt.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được rỗng");
            return null;
        }
        viewModelGioHang.setMaKH(maKH);
        viewModelGioHang.setMaNV(maNV);
        viewModelGioHang.setMa(ma);
        try {
            LocalDate localDate = LocalDate.parse(ngayTao);
            viewModelGioHang.setNgayTao(java.sql.Date.valueOf(localDate));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "chua dung dinh dang ngày tao");
            return null;
        }
        try {
            LocalDate localDate = LocalDate.parse(ngayThanhToan);
            viewModelGioHang.setNgayThanhToan(java.sql.Date.valueOf(localDate));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "chua dung dinh dang ngày thanhtoan");
            return null;
        }
        viewModelGioHang.setDiaChi(diaChi);
        viewModelGioHang.setSoDienThoai(sdt);
        viewModelGioHang.setTenNguoiNhan(tenNguoiNhan);
        return viewModelGioHang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayThanhToan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNguoiNhan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbbMaKH = new javax.swing.JComboBox<>();
        cbbMaNV = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHangFrom = new javax.swing.JTable();
        rdoChoThanhToan = new javax.swing.JRadioButton();
        rdoHuy = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Giỏ Hàng");

        jLabel2.setText("MaKH");

        jLabel3.setText("MaNV");

        jLabel4.setText("Mã");

        jLabel5.setText("Ngày Tạo");

        jLabel6.setText("Ngày Thanh Toán");

        jLabel7.setText("Tên Người Nhận");

        jLabel8.setText("Địa Chỉ");

        jLabel9.setText("Số Điện Thoại");

        jLabel10.setText("Tình Trạng");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblGioHangFrom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " MaKH", "MaNV", "Mã", "Ngày Tạo", "Ngày Thanh Toán", "Tên Người Nhận", "Địa  Chỉ", "Số Điện Thoại", "Tình Trạng", "ID"
            }
        ));
        jScrollPane1.setViewportView(tblGioHangFrom);

        buttonGroup1.add(rdoChoThanhToan);
        rdoChoThanhToan.setText("Chờ thanh toán");

        buttonGroup1.add(rdoHuy);
        rdoHuy.setText("Huỷ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMa)
                                            .addComponent(txtNgayTao)
                                            .addComponent(txtNgayThanhToan)
                                            .addComponent(txtNguoiNhan)
                                            .addComponent(txtDiaChi)
                                            .addComponent(txtSDT)
                                            .addComponent(cbbMaKH, 0, 118, Short.MAX_VALUE)
                                            .addComponent(cbbMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnThem)
                                            .addComponent(jButton2)
                                            .addComponent(btnXoa)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdoChoThanhToan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoHuy)))))
                        .addGap(0, 320, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rdoChoThanhToan)
                    .addComponent(rdoHuy))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ViewModelGioHang viewModelGioHang = getData();
        if (viewModelGioHang == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, iGioHangService.insert(viewModelGioHang));
        loadTable(iGioHangService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       int row = tblGioHangFrom.getSelectedRow();
       String id = tblGioHangFrom.getValueAt(row, 9).toString();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGioHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbMaKH;
    private javax.swing.JComboBox<String> cbbMaNV;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoChoThanhToan;
    private javax.swing.JRadioButton rdoHuy;
    private javax.swing.JTable tblGioHangFrom;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNgayThanhToan;
    private javax.swing.JTextField txtNguoiNhan;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
