/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.ChiTietSP;
import Model.DonHang;
import Repository.ChiTietSPRepository;
import Repository.GioHangRepository;
import Repository.HoaDonChiTietRepository;
import java.awt.Image;
import java.math.BigDecimal;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewChucNangBanHang extends javax.swing.JFrame {

    private ChiTietSPRepository iChiTietSPService = new ChiTietSPRepository();
    private GioHangRepository iGioHangService = new GioHangRepository();
    private HoaDonChiTietRepository iHoaDonService = new HoaDonChiTietRepository();

    /**
     * Creates new form ViewChucNangBanHang
     */
    public ViewChucNangBanHang() {
        initComponents();
        init();
        loadTableSanPham(iChiTietSPService.getListChiTietSP());
        loadTableGioHang(iGioHangService.getAll());
        loadTableHoaDon(iHoaDonService.getAll());

    }

    public void Clean() {
        txtMa.setText("");
        txtNgayTao.setText("");
        txtTenNV.setText("");
        txtTongTien.setText("");
        txtTienKhachDua.setText("");
        txtTienThua.setText("");
    }

    // ảnh logo 
    public class LogoExample {

        public static Image getLoGo() {
            URL url = LogoExample.class.getResource("/image/image/vinmart-có-nhượng-quyền-không.jpg");
            return new ImageIcon(url).getImage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        rdoChoThanhToan = new javax.swing.JRadioButton();
        rdoTatCa = new javax.swing.JRadioButton();
        rdoDaHuy = new javax.swing.JRadioButton();
        rdoDaThanhToan = new javax.swing.JRadioButton();
        btnHoaDon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonForm = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHangForm = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiemTheoTen = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPhamForm = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VinMart");
        setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rdoChoThanhToan);
        rdoChoThanhToan.setText("Chờ thanh toán");
        rdoChoThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChoThanhToanActionPerformed(evt);
            }
        });
        getContentPane().add(rdoChoThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 21, -1, -1));

        buttonGroup1.add(rdoTatCa);
        rdoTatCa.setSelected(true);
        rdoTatCa.setText("tất cả");
        rdoTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTatCaActionPerformed(evt);
            }
        });
        getContentPane().add(rdoTatCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 21, -1, -1));

        buttonGroup1.add(rdoDaHuy);
        rdoDaHuy.setText("Đã huỷ");
        rdoDaHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDaHuyActionPerformed(evt);
            }
        });
        getContentPane().add(rdoDaHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 21, -1, -1));

        buttonGroup1.add(rdoDaThanhToan);
        rdoDaThanhToan.setText("Đã thanh toán");
        rdoDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDaThanhToanActionPerformed(evt);
            }
        });
        getContentPane().add(rdoDaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 21, -1, -1));

        btnHoaDon.setText("Tạo Hoá Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        getContentPane().add(btnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, -1, -1));

        tblHoaDonForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HĐ", "Ngày Tạo", "Tên NV", "Tình Trạng"
            }
        ));
        tblHoaDonForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonFormMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonForm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 70, -1, 129));

        tblGioHangForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane2.setViewportView(tblGioHangForm);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 260, 563, 159));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Giỏ Hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 232, 54, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));

        txtTimKiemTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemTheoTenActionPerformed(evt);
            }
        });
        txtTimKiemTheoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemTheoTenKeyReleased(evt);
            }
        });

        tblSanPhamForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Năm BH", "Mô Tả", "SL SP", "Gía Nhập", "Giá Bán"
            }
        ));
        tblSanPhamForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamFormMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPhamForm);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTimKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemTheoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 459, 563, 262));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Sản Phẩm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 437, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Mã HD");

        txtNgayTao.setEnabled(false);

        jLabel5.setText("Ngày Tạo");

        txtMa.setEnabled(false);

        jLabel6.setText("Tên NV");

        txtTenNV.setEnabled(false);

        jLabel7.setText("Tổng Tiền");

        txtTongTien.setEnabled(false);

        jLabel8.setText("Tiền Khách Đưa");

        txtTienKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKhachDuaActionPerformed(evt);
            }
        });
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyReleased(evt);
            }
        });

        jLabel9.setText("Tiền Thừa");

        txtTienThua.setEnabled(false);

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTienThua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnThanhToan)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 70, -1, 383));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hoá Đơn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 48, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void loadTableHoaDon(ArrayList<DonHang> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblHoaDonForm.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 1;
        for (DonHang viewModelHoaDon : list) {
            defaultTableModel.addRow(new Object[]{
                stt++, viewModelHoaDon.getMa(), viewModelHoaDon.getNgayTao(), viewModelHoaDon.get(), getTinhTrang(viewModelHoaDon.getTinhTrang())

            });
        }
    }

    public String getTinhTrang(int tinhTrang) {
        if (tinhTrang == 0) {
            return "Đã thanh toán";
        } else if (tinhTrang == 1) {
            return "Chờ thanh toán";
        } else {
            return "Đã huỷ";
        }

    }

    // key Release : là sự kiện nhấn từ 1 phím 
    private void txtTimKiemTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemTheoTenActionPerformed
        String searchByTenSanPham = txtTimKiemTheoTen.getText();
        ArrayList<ChiTietSP> sanPham = iChiTietSPService.(searchByTenSanPham);
        loadTableSanPham(sanPham);
    }//GEN-LAST:event_txtTimKiemTheoTenActionPerformed

    private void txtTimKiemTheoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemTheoTenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemTheoTenKeyReleased
    private ArrayList<ViewModelGioHangChucNang> listGioHang = new ArrayList<>();

    private void tblSanPhamFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamFormMouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblSanPhamForm.getModel();
        int row = tblSanPhamForm.getSelectedRow();
        String maSanPham = tblSanPhamForm.getValueAt(row, 1).toString();
        String tenSanPham = tblSanPhamForm.getValueAt(row, 2).toString();
        int soLuong = Integer.parseInt(tblSanPhamForm.getValueAt(row, 5).toString());
        BigDecimal giaBan = new BigDecimal(tblSanPhamForm.getValueAt(row, 7).toString());
        // Kiểm tra số lượng >0 trước khi mouseclick để trừ 
        if (soLuong < 1) {
            JOptionPane.showMessageDialog(this, "Sản phẩm đã hết.");
            return;
        }

        // Giảm số lượng sản phẩm trong bảng sản phẩm đi 1
        tblSanPhamForm.setValueAt(soLuong - 1, row, 5);

        // Tìm sản phẩm trong giỏ hàng
        boolean found = false;
        for (int i = 0; i < listGioHang.size(); i++) {
            //  lấy ra 1 đối tượng 
            ViewModelGioHangChucNang ghct = listGioHang.get(i);
            if (ghct.getMaSP().equals(maSanPham)) {
                found = true;
                ghct.setSoLuong(ghct.getSoLuong() + 1);
                //defaultTableModel.setValueAt(Object aValue, int rowIndex, int columnIndex)
                defaultTableModel.setValueAt(ghct.getSoLuong(), i, 3);
                break;
            }
        }

        // Nếu sản phẩm không tìm thấy trong giỏ hàng thì thêm sản phẩm vào giỏ hàng
        if (!found) {
            ViewModelGioHangChucNang ghct = new ViewModelGioHangChucNang(maSanPham, tenSanPham, 1, giaBan);
            listGioHang.add(ghct);
            defaultTableModel.addRow(new Object[]{maSanPham, tenSanPham, 1, giaBan});
        }

        // Cập nhật số lượng sản phẩm trong cơ sở dữ liệu
        ViewModelChiTietSP viewModelChiTietSP = iChiTietSPService.getSanPhamByMaSP(maSanPham);
        iChiTietSPService.updateSoLuongChiTietSP(soLuong - 1, viewModelChiTietSP.getId());
        // Cập nhật bảng sản phẩm
        loadTableGioHang(listGioHang);
        loadTableSanPham(iChiTietSPService.getAll());


    }//GEN-LAST:event_tblSanPhamFormMouseClicked

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        new ViewHoaDon().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void rdoChoThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChoThanhToanActionPerformed
        int tinhTrang = 1;
        ArrayList<ViewModelHoaDon> list = iHoaDonService.getTenTinhTrang(tinhTrang);
        loadTableHoaDon(list);
    }//GEN-LAST:event_rdoChoThanhToanActionPerformed

    private void rdoTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTatCaActionPerformed
        ArrayList<ViewModelHoaDon> list = iHoaDonService.getAll();
        loadTableHoaDon(list);
    }//GEN-LAST:event_rdoTatCaActionPerformed

    private void rdoDaHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDaHuyActionPerformed
        int tinhTrang = 2;
        ArrayList<ViewModelHoaDon> list = iHoaDonService.getTenTinhTrang(tinhTrang);
        loadTableHoaDon(list);
    }//GEN-LAST:event_rdoDaHuyActionPerformed

    private void rdoDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDaThanhToanActionPerformed
        int tinhTrang = 0;
        ArrayList<ViewModelHoaDon> list = iHoaDonService.getTenTinhTrang(tinhTrang);
        loadTableHoaDon(list);
    }//GEN-LAST:event_rdoDaThanhToanActionPerformed
    BigDecimal tongThanhTien = BigDecimal.ZERO;

    private void tblHoaDonFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonFormMouseClicked

        int row = tblHoaDonForm.getSelectedRow();
        String ma = tblHoaDonForm.getValueAt(row, 1).toString();
        String ngayTao = tblHoaDonForm.getValueAt(row, 2).toString();
        String tenNhanVien = tblHoaDonForm.getValueAt(row, 3).toString();
        txtMa.setText(ma);
        txtNgayTao.setText(ngayTao);
        txtTenNV.setText(tenNhanVien);

        // getRowCount : Số lượng hàng 
        //multiply là 1 phương thức của lớp BigDecimal dùng cho phép nhân 
        if (tongThanhTien.compareTo(BigDecimal.ZERO) == 0) {
            for (int i = 0; i < tblGioHangForm.getRowCount(); i++) {
                BigDecimal gia = new BigDecimal(tblGioHangForm.getValueAt(i, 4).toString());
                int soLuong = Integer.parseInt(tblGioHangForm.getValueAt(i, 3).toString());
                BigDecimal thanhTien = gia.multiply(BigDecimal.valueOf(soLuong));
                tongThanhTien = tongThanhTien.add(thanhTien);
            }
        }
        txtTongTien.setText(tongThanhTien.toString());
    }//GEN-LAST:event_tblHoaDonFormMouseClicked

    private void txtTienKhachDuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyReleased

    }//GEN-LAST:event_txtTienKhachDuaKeyReleased

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        int row = tblHoaDonForm.getSelectedRow();
        String ma = tblHoaDonForm.getValueAt(row, 1).toString();
        if (iHoaDonService.checkTinhTrang(ma) == 0 || iHoaDonService.checkTinhTrang(ma) == 2) {
            JOptionPane.showMessageDialog(this, "Hoá đơn đã huỷ hoặc đã thanh toán");
            return;
        }
        
        try {

            String ngay = txtNgayTao.getText();
            String ten = txtTenNV.getText();
            String tongTien = txtTongTien.getText();
            //  tiền khách đưa dạng String 
            String tienKhach = txtTienKhachDua.getText();
            // ckeck rỗng tiền khách đưa 
            if (tienKhach.trim().equals("") || ma.trim().equals("") || ngay.trim().equals("") || ten.trim().equals("") || tongTien.trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Không được rỗng");
                return;
            }

            // tiền khách đưa khi ép sang kiểu BigDeCimal
            BigDecimal tienKhachDua = new BigDecimal(tienKhach);
            if (tienKhachDua.compareTo(tongThanhTien) < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng trả đủ tiền bạn ơi");
                return;
            }

            BigDecimal tongTienThanhToan = new BigDecimal(txtTongTien.getText());
            // check nhập sai kiểu 

            // trong BigDeCimal không hỗ trợ +,-,*,% mà phải sử dụng khác 
            BigDecimal tienThua = tienKhachDua.subtract(tongTienThanhToan);
            txtTienThua.setText(tienThua.toString());

            // khi thanh toán thành công thì trạng thái chuyển sang đã thanh toán
            iHoaDonService.updateTinhTrang(0, ma);
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
            ArrayList<ViewModelHoaDon> list = iHoaDonService.getAll();
            loadTableHoaDon(list);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tiền khách đưa phải là dạng số");
            return;
        }
        Clean();
        // xoá hết dữ liệu ở các dòng ở table Giỏ hàng 
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblGioHangForm.getModel();
        defaultTableModel.setRowCount(0);

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtTienKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKhachDuaActionPerformed

    }//GEN-LAST:event_txtTienKhachDuaActionPerformed

    public void loadTableSanPham(ArrayList<ViewModelChiTietSP> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblSanPhamForm.getModel();
        defaultTableModel.setRowCount(0);
        int STT = 1;
        for (ViewModelChiTietSP viewModelChiTietSP : list) {
            defaultTableModel.addRow(new Object[]{
                STT++, viewModelChiTietSP.getMaSP(), viewModelChiTietSP.getTenSanPham(), viewModelChiTietSP.getNamBH(), viewModelChiTietSP.getMoTa(), viewModelChiTietSP.getSoLuongTon(), viewModelChiTietSP.getGiaNhap(), viewModelChiTietSP.getGiaBan()
            });
        }
    }

    public void loadTableGioHang(ArrayList<ViewModelGioHangChucNang> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblGioHangForm.getModel();
        defaultTableModel.setRowCount(0);
        int stt = 1;

        for (ViewModelGioHangChucNang viewModelGioHangChucNang : list) {
            defaultTableModel.addRow(new Object[]{
                stt++, viewModelGioHangChucNang.getMaSP(), viewModelGioHangChucNang.getTenSP(), viewModelGioHangChucNang.getSoLuong(), viewModelGioHangChucNang.getDonGia(),
                viewModelGioHangChucNang.getDonGia().multiply(BigDecimal.valueOf(viewModelGioHangChucNang.getSoLuong()))
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChucNangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChucNangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChucNangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChucNangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewChucNangBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoChoThanhToan;
    private javax.swing.JRadioButton rdoDaHuy;
    private javax.swing.JRadioButton rdoDaThanhToan;
    private javax.swing.JRadioButton rdoTatCa;
    private javax.swing.JTable tblGioHangForm;
    private javax.swing.JTable tblHoaDonForm;
    private javax.swing.JTable tblSanPhamForm;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKiemTheoTen;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setIconImage(LogoExample.getLoGo());
        // cho cửa sổ ra giữa 
        this.setLocationRelativeTo(null);
        new ChaoJDiaLog(this, true).setVisible(true);
    }
}
